CREATE DATABASE HOME;
CREATE DATABASE IF NOT EXISTS HOME;

USE HOME;

CREATE TABLE book (
	serial INT PRIMARY KEY,
    name VARCHAR(50),
    writer VARCHAR(50)
);

INSERT INTO book VALUES (1,"SOFTWARE ENGINEERING","PRESSMAN");
INSERT INTO book VALUES (2,"DBMS","SUDARSHAN");

SELECT * FROM book;

SHOW DATABASES;
SHOW TABLES;

/*DROP DATABASE HOME;*/
